In [ ]:
import torch

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"  # Cuda to run on GPU!

In [ ]:
var_tensor = torch.tensor(
    [[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device, requires_grad=True
)

In [ ]:
print({var_tensor}, {var_tensor.dtype}, {var_tensor.device}, {var_tensor.shape},{var_tensor.requires_grad} )

{tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)} {torch.float32} {device(type='cpu')} {torch.Size([2, 3])} {True}


In [ ]:
torch.empty(size=(3, 3))

tensor([[2.0649e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22]])

In [ ]:
torch.zeros((3, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.rand((3, 3))

tensor([[0.1675, 0.5753, 0.0574],
        [0.1027, 0.4189, 0.9236],
        [0.6538, 0.7564, 0.0538]])

In [ ]:
torch.ones((3, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.eye(5, 5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.arange(start=0, end=5, step=1)

tensor([0, 1, 2, 3, 4])

In [ ]:
torch.linspace(start=0.1, end=1, steps=5)

tensor([0.1000, 0.3250, 0.5500, 0.7750, 1.0000])

In [ ]:
# Normally distributed with mean=0, std=1
torch.empty(size=(1, 5)).normal_(mean=0, std=1)

tensor([[-0.8915, -1.8314,  1.8491, -1.3352,  1.2389]])

In [ ]:
 torch.diag(torch.ones(3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
var_tensor = torch.arange(4)
print(var_tensor.bool())
print(var_tensor.half())
print(var_tensor.float())

tensor([False,  True,  True,  True])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])


In [ ]:
import numpy as np

np_array = np.zeros((5, 5))
print("np_array : ", np_array)
tensor = torch.from_numpy(np_array)
print("tensor : ", tensor)
np_array_again = (tensor.numpy())
print("np again : ", np_array_again)

np_array :  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor :  tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
np again :  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
x = torch.tensor([2, 3, 4])
y = torch.tensor([7, 6, 5])

In [ ]:
z1 = torch.empty(3)
print("Way 1 : ",torch.add(x, y, out=z1))
z2 = torch.add(x, y)
print("Way 2 : ", z2)
z = x + y
print("Way 3 : ", z)

#similarly we can do subtraction and division

Way 1 :  tensor([9., 9., 9.])
Way 2 :  tensor([9, 9, 9])
Way 3 :  tensor([9, 9, 9])


In [ ]:
print("Way 1 : ", x.pow(2))
print("Way 2 : ",x ** 2)

Way 1 :  tensor([ 4,  9, 16])
Way 2 :  tensor([ 4,  9, 16])
